<?php
$page->addToDrobeckovaNavigace('<a href="index.php?page=uniformy&subpage=ww2">WW2</a>');
$page->addToDrobeckovaNavigace('<a href="index.php?page=uniformy&subpage=ww2&category=medaile">Medaile a vyznamenání</a>');
$page->setTitle("Medaile a vyznamenání | KVH Ústí nad Labem");
$container = "<h2>Kampaňové medaile Británie a Commonwealthu za 2. svět. válku</h2>";

$container .= '<p>Každá armáda chce ocenit svého vojáka za jeho počínání ve válečném konfliktu. Konflikt druhá světová válka je přeci jen konfliktem vážným a těžším než jiné konflikty, tudíž ministerstvo války chtělo pamatovat na všechny a přišlo s následujícími medailemi. Tyto jsou udělované všem složkám i hodnostem vojáků (nejen) Commonwealthu. Zpravidla se udělují s dekretem v papírové krabičce s razítkem korunky krále a strojově vyplněným jménem. Medaile kruhové mají v průměru 36mm, šesticípé hvězdy mají ve svém středu monogram krále Jiřího VI. (GRJVI), na vrcholku s královskou korunkou. Okolo monogramu je název každé medaile.</p>';

$container .= '<a href="images/uniformy/medaile/1.jpg"  rel="lightbox[uniform]"><img src="images/uniformy/medaile/1.jpg" class="ilustrace_float"></a>';
$container .= '<a href="images/uniformy/medaile/2.jpg"  rel="lightbox[uniform]"><img src="images/uniformy/medaile/2.jpg" class="ilustrace_float"></a>';

$container .= '<ol>';
$container .= '<li><h3>Důstojnická hodnost</h3><p>uchycuje se zezadu na dvě očka pro provlečení špendlíku, jedna takováto pecka = Second-Lieutenant</p></li>';
$container .= '<li><h3>Victory pin</h3><p>vítězný špendlík belgické civilní produkce, v civilu nošen kdekoli na klopě či kožené palubní desce automobilu; vojáci je po podepsání kapitulace v Evropě nosili proti předpisům v levém rohu límce battledressu či na klopě levé náprsní kapsy.</p></li>';
$container .= '<li><h3>Defence medal (medaile za obranu)</h3><p>udělována od 16. října 1945 za tříletou službu ve Velké Británii nebo rok v zahraničí mimo bojiště či šest měsíců v zahraničí blízko bojiště či přímo v náletové zóně. Aktivní ve službě do roku 1943 ji mají automaticky letecké složky a domobrana, dále se uděluje také pobřežní stráži, policii, balónovým jednotkám a požárním jednotkám včetně těch v National Defence (národní obrana). Na stužce se objevuje pouze v civilní verzi stříbrný vavřín, kterým se vyznačuje uznání Krále za statečné chování. Udělována až po válce</p></li>';
$container .= '<li><h3>War Medal 1939-45 (válečná medaile)</h3><p>udělována všem kdo sloužili celých 28 dní v ozbrojených silách či obchodním loďstvu. Bývá častá i varianta se stříbrnou dubovou ratolestí (včetně stužky), což značí, že nositel této medaile byl uveden/citován v hlášení. Udělována až po válce.</p></li>';
$container .= '<li><h3>the 1939-1945 Star</h3><p>(ustanovena v červenci 1943 jako 1939-1943 Star) udělována za službu mezi 3. září 1939 až 2. září 1945. Pozemní jednotky na ni mají nárok po šesti měsících, letecké jednotky po dvou měsících služby. Na medaili se je možnost lišty BATTLE OF BRITAIN, na stužce pak stříbrná pětilistá růže za účast v Bitvě o Británii. Udělována až po válce.</p>
        <p>* Zde na fotce jsou Defence a War medal upřednostněny před kampaňovými hvězdami pro lepší vizualizaci. Správně dle faleristických pravidel jsou kampaňové medaile před výročními, služebními, výročními medailemi.</p></li>';
$container .= '<li><h3>the Africa Star</h3><p>udělována všem, kdo sloužili na území Severní Afriky mezi 10. červnem 1940 až 12. květnem 1943. Pro sloužící na Maltě, v Gibraltaru, Suezu, Súdánu, Habeši, Keně, Somálsku, Eritreji a ve Středozemním moři (včetně výsostných italských vod) mezi 10. červnem 1940 a 27. listopadem 1941. Tato medaile má tři druhy lišt. NORTH AFRICA 1942-43 pro službu v tomto období (převážně jednotky Commonwealthu), 1st ARMY pro příslušníky 1. Armády a 8th ARMY pro příslušníky 8. Armády. Na stužce (miniatuře) se našívají pouze stříbrná čísla 1 nebo 8 dle lišty. Udělována od roku 1943.</p></li>';
$container .= '<li><h3>the Italy Star</h3><p>Italská hvězda udělována za účast na území Itálie (včetně ostrovů Elby, Korsiky, Pantallerie a Sicílie), území Jugoslávie, Řecka a všech jejich ostrovů i moří mezi nimi, mezi 11. srpnem 1943 až 5. květnem 1945. Ustanovena v květnu 1945 a tudíž udělována po válce.</p></li>';
$container .= '<li><h3>the France and Germany Star</h3><p>Hvězda Francie a Německa udělována za jeden či více dní pobytu ve Francii, Lucemburku, Belgii, Nizozemí, Německu (neplatí pro Rakousko) a v Severním moři mezi 6. červnem 1944 až 8. květnem 1945. Tato medaile má možnou lištu s nápisem ATLANTIC, za působení v oblasti od nejjižnějšího cípu Norska, v Severním moři, průlivu La Manche až po 6° západní délky v Biskajském zálivu. Ustanovena v květnu 1945, udělována po válce. Na miniatuře (stužce) se objevuje pětilistá růže za citování v rozkaze.</p></li>';
$container .= '<li><h3>the Burma Star</h3><p>Burmská hvězda byla udělována za účast na území Sumatry, Malaisie, Hong Kongu a Číny. Pro Burmskou kampaň mezi 11. prosincem 1941 a 2. září 1945. Tato medaile má lištu s nápisem PACIFIC, pro ty, kteří splnili požadavky pro the Pacific Star (na miniatuře pětilistou růži). Ustanovena v květnu 1945, udělována až po válce.</p></li>';
$container .= '<li><h3>the Pacific Star</h3><p>Hvězda Pacifiku byla udělována za účast na území Sumatry, Malaisie, Hong Kongu, Číny, Tichého oceánu (včetně Čínského Jižního moře), Indického oceánu, Vánočních ostrovů až po 110° východní délky. Medaile má lištu s nápisem BURMA (a na miniatuře pětilistou růži) pro ty, kteří splnili požadavky pro the Burma Star. Ustanovena v květnu 1945, udělována až po válce.</p></li>';
$container .= '<li><h3>the Atlantic Star</h3><p>Hvězda Atlantiku byla udělována ihned po smrti, zraněni nebo jmenování v hlášení během šesti měsíců služby na vodě v Atlantiku (v celé jeho rozloze) či domácích vodách v období mezi 3. září 1939 až 8. květnem 1945. Medaile má lištu AIR CREW EUROPE pro letecké jednotky jak pobřežní stráže, tak i letadlových lodí, nebo lištu FRANCE and GERMANY. Na stužce pak stříbrná pětilistá růže. Ustanovena v květnu 1945, udělována až po válce.</p></li>';
$container .= '<li><h3>the Air Crew Europe Star</h3><p>tato hvězda byla udělována posádkám letadel, která operovala z britských letišť v období 2. září 1939 až 5. červen 1944. Medaile má lištu s nápisem ATLANTIC pro ty, jež splňují podmínky pro the Atlantic star a lištu s nápisem FRENCH and GERMANY pro operační lety přes Evropu. Na stužce je pak stříbrná pětilistá růže. Ustanovena v květnu 1945, udělována až po válce.</p></li>';
$container .= '<li><h3>the Arctic Star</h3><p>byla ustanovena v prosinci 2012, udělována od března 2013 za delší operační služby severně od polárního kruhu (ustanovující rozkaz přesně stanovuje 66°a 32‘ severní šířky) pro příslušníky Královského námořnictva, příslušníků ozbrojených sil i obchodního námořnictva včetně civilních příslušníků konvojů v době mezi 3. září 1939 – 8. květnem 1945. Přednost udělení mají ti příslušníci, kteří neobdrželi Atlantic Star, Air Crew Europe Star nebo jiný ekvivalent své země za tyto služby (především Royal Canadian Navy). Nosí se mezi Atlantic star a Air Crew Europe star.</p></li>';
$container .= '</ol>';

$container .= "<div><h4>Zdroje:</h4>
                <ul>
                    <li>E. C. Joslin, the Observer‘s book of British Awards and Medals, Frederick Wayne & Co. Ltd. London 1974, ISBN: 0-7232-1538-3</li>
                    <li>R. W. Gould, the British Campaign Medals Waterloo to the Falklands, Arms & Armour Ltd. London 1986, ISBN: 0-8536-8672-6</li>
                    <li>Bouchery J. The British Tommy in nort west Europe 1944-1945, volume 1, Historie & Collections, Paris 1998, ISBN: 2-908182-44-0</li>
                    <li>the Arctic Star, Online 4.3.2016, <a href='https://en.wikipedia.org/wiki/Arctic_Star' target='_blank'>https://en.wikipedia.org/wiki/Arctic_Star</a></li>
                    <li><a href='http://www.militaryimages.net/media/the-arctic-star.81006/' target='_blank'>http://www.militaryimages.net/media/the-arctic-star.81006/</a></li>
                </ul>
                </div>";

return $container;